import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_about: 'About',
    nav_services: 'Services',
    nav_products: 'Products',
    nav_contact: 'Contact',
    nav_brochure: 'Brochure',
    nav_phone: '+91 99446 77149',
    lang_toggle_label: 'Switch to Tamil',

    // Navbar Mega Menu
    mega_footer_badge: 'Varatha Vinayagar Safety & Fire',
    mega_footer_desc: 'Need specialized high-pressure testing, gas release panels, or bespoke safety installations? We provide standard-compliant setup.',
    mega_footer_btn: 'Get Free Consultation',
    mobile_emergency_label: '24/7 Emergency Support',

    // Home Hero Slides
    hero_iso_certification: 'AN ISO 9001:2015 | ISO 45001:2018 CERTIFIED COMPANY',
    hero_slide0_tagline: "Tuticorin's Premium Fire Safety Partner",
    hero_slide0_title: 'Advanced Fire',
    hero_slide0_accent: 'Extinguishers',
    hero_slide0_desc: 'Premium BIS-approved ABC Powder, CO₂, Foam & Clean Agent systems. Complete refilling, hydrostatic testing, and servicing with absolute standard compliance.',
    hero_slide0_cta1: 'Explore Products',
    hero_slide0_cta2: 'Get Consultation',

    hero_slide1_tagline: 'Precision Early-Warning Smoke Alerting',
    hero_slide1_title: 'Intelligent Alarm',
    hero_slide1_accent: 'Systems',
    hero_slide1_desc: 'State-of-the-art addressable panels, optical smoke detectors, rate-of-rise heat sensors, and automated gas release systems for early warning hazard protection.',
    hero_slide1_cta1: 'View Systems',
    hero_slide1_cta2: 'Request Safety Audit',

    hero_slide2_tagline: 'Heavy-Duty Emergency Control Systems',
    hero_slide2_title: 'Hydrant & Suppression',
    hero_slide2_accent: 'Gear',
    hero_slide2_desc: 'High-pressure landing valves, 2-way/4-way fire hydrants, durable hose reel systems, heavy-duty foam monitors, and high trajectory water stream monitors.',
    hero_slide2_cta1: 'Explore Hydrants',
    hero_slide2_cta2: 'Get Free Quote',

    // Home
    home_badge: 'Varatha Vinayagar Safety & Fire',
    home_hero_h2: 'Complete',
    home_hero_h2_span: 'Fire Safety',
    home_hero_h2_end: 'Solutions',
    home_hero_p: "Tuticorin's premium partner for Refilling, Servicing & H.P. Testing. We don't just sell equipment; we sell peace of mind.",
    home_btn_consultation: 'Get Consultation',
    home_btn_brochure: 'Download Brochure',

    home_cat_badge: 'Featured Categories',
    home_cat_title: 'Explore Our',
    home_cat_title_span: 'Safety',
    home_cat_title_end: 'Range',

    // Home Category Names
    cat_fire_extinguishers: 'Fire Extinguisher and Spares',
    cat_fire_alarm: 'Fire Alarm Systems and Accessories',
    cat_hydrant: 'Fire Hydrant System Installation and Accessories',
    cat_ppe: 'Safety Products (PPE)',
    cat_road_safety: 'Road Safety Products',
    cat_suppression: 'Fire Suppression',

    // Industries We Serve
    home_industries_badge: 'Industries We Serve',
    home_industries_title: 'Delivering Trusted',
    home_industries_title_span: 'Fire Safety & Compliance',
    home_industries_desc: 'Delivering trusted fire safety and compliance solutions across diverse industries.',
    ind_ports_title: 'Ports',
    ind_ports_desc: 'Fire protection for docks, warehouses & cargo facilities.',
    ind_power_title: 'Power Plants',
    ind_power_desc: 'Ensuring fire safety & continuity in energy generation sites.',
    ind_substations_title: 'Substations',
    ind_substations_desc: 'Specialized fire systems for critical electrical assets.',
    ind_chemical_title: 'Chemical Plants',
    ind_chemical_desc: 'Fire suppression for flammable & hazardous environments.',
    ind_refineries_title: 'Refineries',
    ind_refineries_desc: 'Protecting oil & gas assets with advanced fire solutions.',
    ind_petrochemicals_title: 'Petrochemicals',
    ind_petrochemicals_desc: 'Comprehensive detection & suppression for petro industries.',
    ind_fertilizer_title: 'Fertilizer Plants',
    ind_fertilizer_desc: 'Explosion-proof fire safety for chemical processing units.',
    ind_paint_title: 'Paint Factories',
    ind_paint_desc: 'Fire solutions for solvent-heavy paint manufacturing units.',
    ind_automobile_title: 'Automobile Plants',
    ind_automobile_desc: 'Fire suppression across assembly lines & test bays.',
    ind_paper_title: 'Paper Mills',
    ind_paper_desc: 'Preventing fires in high-dust, high-combustion areas.',
    ind_it_title: 'IT Companies',
    ind_it_desc: 'Data center fire suppression & business continuity solutions.',
    ind_hospitals_title: 'Hospitals',
    ind_hospitals_desc: 'Protecting critical care facilities & ensuring safe evacuation.',
    ind_defense_title: 'Defense Installations',
    ind_defense_desc: 'Mission-critical fire safety for defense infrastructure.',
    ind_nuclear_title: 'Nuclear Plants',
    ind_nuclear_desc: 'Compliance-based fire suppression for nuclear sites.',
    ind_aircraft_title: 'Aircraft Facilities',
    ind_aircraft_desc: 'Comprehensive protection for hangars & aerospace units.',

    // Licenses & Approvals
    home_licenses_badge: 'Licenses & Approvals',
    home_licenses_title: 'Expert in',
    home_licenses_title_span: 'Licenses & Approvals',
    home_licenses_desc: 'We provide certified, government-approved fire safety licenses and compliance services that keep your business audit-ready.',
    lic_noc_title: 'Govt. Fire NOC',
    lic_noc_desc: 'End-to-end assistance for fire department approvals & No Objection Certificates.',
    lic_iso_title: 'BIS & ISO Certified',
    lic_iso_desc: 'Fully approved products & services that meet national and international standards.',
    lic_audits_title: 'Compliance Audits',
    lic_audits_desc: 'On-site inspections, compliance reports, and documentation for approvals.',
    lic_approvals_title: 'Industry Approvals',
    lic_approvals_desc: 'Licensing for factories, malls, hospitals, IT parks, and other industries.',

    // Areas of Operation
    about_operation_badge: 'Service Coverage',
    about_operation_title: 'Our Areas of',
    about_operation_title_span: 'Operation',
    about_operation_desc: 'Supplying premium fire protection equipment and compliance services across major cities of Tamil Nadu.',
    about_operation_subtitle: 'Supply & Service Network',

    home_about_badge: 'Welcome to Varatha Vinayagar',
    home_about_h1: 'Your Trusted Partner in',
    home_about_h1_span: 'Safety',
    home_about_p1: 'We supply advanced fire extinguishers, hydrant accessories, personal protective equipment, and industrial safety products based in Tuticorin.',
    home_about_p2: 'Our products strictly follow high-quality standards, guaranteeing durability, and user-friendly design with a strong focus on absolute customer satisfaction.',
    home_about_btn: 'Learn More About Us',

    stat_compliance: 'Safety Compliance',
    stat_experience: 'Years Experience',
    stat_staff: 'Certified Staff',
    stat_sites: 'Active Sites',
    stat_satisfaction: 'Customer Satisfaction',
    stat_customers: 'Happy Customers',

    home_process_badge: 'Our Process',
    home_process_title: 'How We',
    home_process_title_span: 'Work',
    step_inspection: 'Inspection',
    step_collection: 'Collection',
    step_execution: 'Execution',
    step_delivery: 'Delivery',
    step_inspection_desc: 'Thorough site assessment and hazard identification.',
    step_collection_desc: 'Safe transport of equipment to our certified facility.',
    step_execution_desc: 'Certified refill and high-pressure testing.',
    step_delivery_desc: 'Final quality check and prompt delivery.',

    home_why_badge: 'Why Us',
    home_why_title: 'Reliability in Every',
    home_why_title_span: 'Second',
    why_compliance: 'Standard Compliance',
    why_compliance_desc: 'Licensed by Industrial Safety Standards for full compliance.',
    why_support: '24/7 Support',
    why_support_desc: 'Round-the-clock emergency response for all safety needs.',
    why_certified: 'Certified Handling',
    why_certified_desc: 'Expert technicians with decades of collective experience.',

    // Home Testimonials
    home_testimonials_badge: 'Client Reviews',
    home_testimonials_title: 'Trusted by',
    home_testimonials_title_span: 'Hundreds',
    home_testimonials_title_end: 'Across Tamil Nadu',

    // Home Partners
    home_partners_badge: 'Authorised Partners',
    home_partners_title: 'Trusted Brands &',
    home_partners_title_span: 'Certifications',

    // Services
    services_badge: 'Our Expertise',
    services_h1: 'Complete',
    services_h1_span: 'Safety',
    services_h1_end: 'Services',
    services_intro: 'We provide a comprehensive range of professional fire safety services to keep your environments fully protected.',

    svc_supply_title: 'Fire Extinguisher Supply',
    svc_supply_desc: 'Delivering world-class, certified fire extinguishers perfectly suited for industrial, commercial, and residential use.',
    svc_refill_title: 'Fire Extinguisher Refilling',
    svc_refill_desc: 'High-quality refilling agents matching stringent industry standards for rapid fire suppression.',
    svc_service_title: 'Fire Extinguisher Servicing',
    svc_service_desc: 'Periodic servicing by qualified technicians to ensure your equipment is always ready.',
    svc_hptest_title: 'High Pressure Testing',
    svc_hptest_desc: 'Advanced hydrostatic testing ensuring container integrity under extreme conditions.',
    svc_install_title: 'Fire Safety Equipment Installation',
    svc_install_desc: 'Precision installation of fire safety pipelines, hydrants, and complete fire protection systems.',
    svc_amc_title: 'Annual Maintenance Contracts (AMC)',
    svc_amc_desc: 'End-to-end periodic maintenance checks for complete peace of mind.',
    svc_industrial_title: 'Industrial Safety Solutions',
    svc_industrial_desc: 'We specialize in heat protective garments, safety showers, and fall protection gear specifically for industries.',

    industries_badge: 'Where We Serve',
    industries_title: 'Industries',
    industries_title_span: 'Served',

    ind_steel: 'Steel & Iron Industries',
    ind_thermal: 'Thermal Power Plants',
    ind_construction: 'Construction & Infrastructure',
    ind_engineering: 'Engineering Industries',
    ind_textile: 'Textile & Garment Industries',
    ind_chemical: 'Chemical Industries',
    ind_government: 'Government Sector',
    ind_education: 'Educational Institutions',

    cta_title: 'Ready to secure your premises?',
    cta_desc: 'Contact us today for an expert consultation and a tailored safety solution for your industry.',
    cta_btn: 'Book Consultation',

    // Products
    products_badge: 'Our Catalog',
    products_h1: 'Premium Safety',
    products_h1_span: 'Products',
    products_all: 'All',
    enquire_now: 'Enquire Now',

    // About
    about_partner_badge: 'Authorized Partners',
    about_partner_title: 'Trusted Brands &',
    about_partner_title_span: 'Certifications',
    about_badge: 'Our Company Profile',
    about_h1: 'Varatha Vinayagar',
    about_h1_span: 'Safety & Fire',
    about_p1: 'We supply fire extinguishers, hydrant accessories, personal protective equipment, and industrial safety products based in Tuticorin.',
    about_p2: 'Our products follow high-quality standards, durability, and user-friendly design with a strong focus on customer satisfaction and fast service delivery.',
    about_check1: 'Strict quality control from design to testing',
    about_check2: 'Advanced technology integration',
    about_check3: 'Skilled professionals and experienced team',
    about_check4: 'Customer-centric service approach',
    about_vision_title: 'Our Vision',
    about_mission_title: 'Our Mission',
    about_quality_title: 'Quality Policy',

    about_vision_desc: 'To become a highly respected safety solutions provider delivering:',
    about_vision_1: 'Complete safety systems and services',
    about_vision_2: 'Advanced technology-based solutions',
    about_vision_3: 'Continuous improvement and innovation',
    about_vision_4: 'Strong customer-focused approach',

    about_mission_desc: 'Driving excellence via:',
    about_mission_1: "Achieve top position in India's safety industry",
    about_mission_2: 'Focus on innovation, quality, and service excellence',
    about_mission_3: 'Promote safety awareness and responsibility',
    about_mission_4: 'Deliver high-value products and solutions',

    about_quality_desc: 'We ensure quality through:',
    about_quality_1: 'Strict quality control from design to testing',
    about_quality_2: 'Advanced technology integration',
    about_quality_3: 'Skilled professionals and experienced team',
    about_quality_4: 'Customer-centric service approach',

    // About Infrastructure
    infra_badge: 'Physical Capacity',
    infra_title: 'Our',
    infra_title_span: 'Infrastructure',
    infra_p1: 'Varatha Vinayagar Safety & Fire boasts a state-of-the-art facility located in Tuticorin, fully equipped for heavy industrial operations. Our setup is tailored specifically to deliver rapid, reliable services for fire protection assets.',
    infra_p2: 'Our infrastructure features a high-capacity warehouse, professional service bays, and dedicated hydrostatic testing manifolds. We use automated dry powder refilling machines, highly accurate weight-calibrated gas filling systems, and high-pressure nitrogen/carbon dioxide chargers. This ensures every fire extinguisher refilled, serviced, or tested at our site satisfies stringent national and industrial safety guidelines.',
    infra_check1: 'High-capacity modern refilling workshop',
    infra_check2: 'Certified hydrostatic testing manifolds',
    infra_check3: 'Fully calibrated weight-checking & pressure gauges',

    // Contact
    contact_hero_badge: 'Direct Terminals',
    contact_hero_title_1: 'Reach Out to Our',
    contact_hero_title_span: 'Safety Protocol',
    contact_hero_title_2: 'Team',
    contact_hero_desc: 'Have an urgent safety requirement, extinguisher refilling request, or system installation query? Our certified fire safety engineers are standby 24/7 to provide rapid support, quotes, and structural hazard consultation.',
    contact_call_btn: 'Call Emergency Team',
    contact_quote_btn: 'Request Free Quote',

    contact_support_badge: 'Support Options',
    contact_support_title_1: 'Send a',
    contact_support_title_span: 'Direct Terminal',
    contact_support_title_2: 'Query',

    contact_badge: 'Get in Touch',
    contact_h1: 'Contact',
    contact_h1_span: 'Safety',
    contact_h1_end: 'Team',
    contact_phones: 'Phone Numbers',
    contact_email: 'Email',
    contact_email_btn: 'Email Us',
    contact_location: 'Location',
    contact_location_addr: '112Q/3, Muthukrishnapuram 2nd Street, Tuticorin, Tamil Nadu',
    contact_emergency: 'Emergency Service',
    contact_emergency_avail: '24/7 Availability',
    contact_emergency_desc: 'Our team is fully equipped and on standby around the clock for rapid emergency response.',
    contact_form_title: 'Request a Quote',
    contact_name: 'Full Name',
    contact_name_placeholder: 'John Doe',
    contact_phone_label: 'Contact Number',
    contact_phone_placeholder: '+91 00000 00000',
    contact_service: 'Service Required',
    contact_svc_refilling: 'Refilling',
    contact_svc_servicing: 'Servicing',
    contact_svc_hptesting: 'H.P. Testing',
    contact_svc_supply: 'Equipment Supply',
    contact_message: 'Message',
    contact_message_placeholder: 'Tell us about your requirements...',
    contact_send: 'Send Message',
    contact_email_label: 'Email Address',
    contact_get_in_touch: 'Get In Touch',
    contact_protect_desc: 'Ready to protect what matters most? Contact our fire safety experts for a free consultation and customized fire protection solution.',
    contact_form_free_quote: 'Request a Free Quote',

    // Footer
    footer_brand_sub: 'SAFETY & FIRE',
    footer_motto: '"Never Trust Fire! Trust Varatha Vinayagar Safety & Fire - Your Structural Integrity Guard."',
    footer_gstin_label: 'GSTIN REGISTERED',
    footer_nav: 'Navigation',
    footer_terminals: 'Data Terminals',
    footer_copy: 'VV Safety & Fire. Protocol Status: SECURE',
    footer_tagline: 'Reliability | Integrity | Structural Protection',
  },

  ta: {
    // Navbar
    nav_home: 'முகப்பு',
    nav_about: 'எங்களை பற்றி',
    nav_services: 'சேவைகள்',
    nav_products: 'தயாரிப்புகள்',
    nav_contact: 'தொடர்பு',
    nav_brochure: 'சிறுநூல்',
    nav_phone: '+91 99446 77149',
    lang_toggle_label: 'Switch to English',

    // Navbar Mega Menu
    mega_footer_badge: 'வரத விநாயகர் பாதுகாப்பு & தீ',
    mega_footer_desc: 'சிறப்பு உயர் அழுத்த சோதனை, வாயு வெளியீட்டு பேனல்கள் அல்லது தனிப்பயன் பாதுகாப்பு நிறுவல்கள் தேவையா? தர இணக்கமான அமைப்பை வழங்குகிறோம்.',
    mega_footer_btn: 'இலவச ஆலோசனை பெறுக',
    mobile_emergency_label: '24/7 அவசர ஆதரவு',

    // Home Hero Slides
    hero_iso_certification: 'AN ISO 9001:2015 | ISO 45001:2018 சான்றளிக்கப்பட்ட நிறுவனம்',
    hero_slide0_tagline: 'தூத்துக்குடியின் முன்னணி தீ பாதுகாப்பு பங்காளி',
    hero_slide0_title: 'மேம்பட்ட தீ',
    hero_slide0_accent: 'அணைப்பான்கள்',
    hero_slide0_desc: 'BIS-அங்கீகரிக்கப்பட்ட ABC பொடி, CO₂, நுரை & சுத்தமான முகவர் அமைப்புகள். முழுமையான நிரப்புதல், ஹைட்ரோஸ்டாடிக் சோதனை மற்றும் தரநிலை இணக்கத்துடன் சேவை.',
    hero_slide0_cta1: 'தயாரிப்புகளை ஆராயுங்கள்',
    hero_slide0_cta2: 'ஆலோசனை பெறுக',

    hero_slide1_tagline: 'துல்லியமான முன்கூட்டிய எச்சரிக்கை புகை எச்சரிப்பு',
    hero_slide1_title: 'புத்திசாலி எச்சரிக்கை',
    hero_slide1_accent: 'அமைப்புகள்',
    hero_slide1_desc: 'அதிநவீன முகவரியிடக்கூடிய பேனல்கள், ஒளியியல் புகை கண்டறிப்பான்கள், வெப்பநிலை உணர்விகள் மற்றும் தானியங்கி வாயு வெளியீட்டு அமைப்புகள்.',
    hero_slide1_cta1: 'அமைப்புகளைக் காண்க',
    hero_slide1_cta2: 'பாதுகாப்பு ஆய்வு கோரிக்கை',

    hero_slide2_tagline: 'கனரக அவசர கட்டுப்பாட்டு அமைப்புகள்',
    hero_slide2_title: 'ஹைட்ரன்ட் & அடக்குதல்',
    hero_slide2_accent: 'உபகரணங்கள்',
    hero_slide2_desc: 'உயர் அழுத்த தரையிறக்க வால்வுகள், 2-வழி/4-வழி தீ ஹைட்ரன்ட்கள், நீடித்த குழாய் ரீல் அமைப்புகள், கனரக நுரை கண்காணிப்பான்கள்.',
    hero_slide2_cta1: 'ஹைட்ரன்ட்களை ஆராயுங்கள்',
    hero_slide2_cta2: 'இலவச மதிப்பீடு பெறுக',

    // Home
    home_badge: 'வரத விநாயகர் பாதுகாப்பு & தீ சேவை',
    home_hero_h2: 'முழுமையான',
    home_hero_h2_span: 'தீ பாதுகாப்பு',
    home_hero_h2_end: 'தீர்வுகள்',
    home_hero_p: 'தூத்துக்குடியின் முன்னணி பங்காளி — நிரப்புதல், சேவை & உயர் அழுத்த சோதனை. உபகரணம் மட்டுமல்ல, மன அமைதியும் வழங்குகிறோம்.',
    home_btn_consultation: 'ஆலோசனை பெறுக',
    home_btn_brochure: 'சிறுநூல் பதிவிறக்கம்',

    home_cat_badge: 'சிறப்பு வகைகள்',
    home_cat_title: 'எங்கள்',
    home_cat_title_span: 'பாதுகாப்பு',
    home_cat_title_end: 'வரம்பை ஆராயுங்கள்',

    // Home Category Names
    cat_fire_extinguishers: 'தீ அணைப்பான்கள் மற்றும் உதிரிபாகங்கள்',
    cat_fire_alarm: 'தீ எச்சரிக்கை அமைப்புகள் மற்றும் பாகங்கள்',
    cat_hydrant: 'தீ ஹைட்ரண்ட் சிஸ்டம் நிறுவல் மற்றும் பாகங்கள்',
    cat_ppe: 'பாதுகாப்பு பொருட்கள் (PPE)',
    cat_road_safety: 'சாலை பாதுகாப்பு பொருட்கள்',
    cat_suppression: 'தீ அடக்குதல்',

    // Industries We Serve
    home_industries_badge: 'நாங்கள் சேவை செய்யும் தொழில்கள்',
    home_industries_title: 'நம்பகமான',
    home_industries_title_span: 'தீ பாதுகாப்பு & இணக்கம்',
    home_industries_desc: 'பல்வேறு தொழில்களில் நம்பகமான தீ பாதுகாப்பு மற்றும் இணக்க தீர்வுகளை வழங்குதல்.',
    ind_ports_title: 'துறைமுகங்கள்',
    ind_ports_desc: 'கப்பல்துறைகள், கிடங்குகள் மற்றும் சரக்கு வசதிகளுக்கான தீ பாதுகாப்பு.',
    ind_power_title: 'மின் உற்பத்தி நிலையங்கள்',
    ind_power_desc: 'மின் உற்பத்தி தளங்களில் தீ பாதுகாப்பு மற்றும் தொடர்ச்சியை உறுதி செய்தல்.',
    ind_substations_title: 'துணை மின் நிலையங்கள்',
    ind_substations_desc: 'முக்கியமான மின்சார சொத்துக்களுக்கான சிறப்பு தீயணைப்பு அமைப்புகள்.',
    ind_chemical_title: 'இரசாயன ஆலைகள்',
    ind_chemical_desc: 'எரியக்கூடிய மற்றும் அபாயகரமான சூழல்களுக்கான தீயணைப்பு.',
    ind_refineries_title: 'சுத்திகரிப்பு நிலையங்கள்',
    ind_refineries_desc: 'மேம்பட்ட தீ தீர்வுகள் மூலம் எண்ணெய் மற்றும் எரிவாயு சொத்துக்களை பாதுகாத்தல்.',
    ind_petrochemicals_title: 'பெட்டோகெமிக்கல்ஸ்',
    ind_petrochemicals_desc: 'பெட்ரோலிய தொழில்களுக்கான விரிவான கண்டறிதல் மற்றும் அடக்குதல்.',
    ind_fertilizer_title: 'உர ஆலைகள்',
    ind_fertilizer_desc: 'இரசாயன செயலாக்க பிரிவுகளுக்கான வெடிப்பு-தடுப்பு தீ பாதுகாப்பு.',
    ind_paint_title: 'பெயிண்ட் தொழிற்சாலைகள்',
    ind_paint_desc: 'கரைப்பான்-அடர்ந்த பெயிண்ட் தயாரிப்பு அலகுகளுக்கான தீ தீர்வுகள்.',
    ind_automobile_title: 'ஆட்டோமொபைல் ஆலைகள்',
    ind_automobile_desc: 'அசெம்பிளி லைன்கள் மற்றும் சோதனை விரிகுடாக்கள் முழுவதும் தீயணைப்பு.',
    ind_paper_title: 'காகித ஆலைகள்',
    ind_paper_desc: 'அதிக தூசி, அதிக எரிப்பு பகுதிகளில் தீயை தடுத்தல்.',
    ind_it_title: 'IT நிறுவனங்கள்',
    ind_it_desc: 'தரவு மைய தீயணைப்பு மற்றும் வணிக தொடர்ச்சி தீர்வுகள்.',
    ind_hospitals_title: 'மருத்துவமனைகள்',
    ind_hospitals_desc: 'தீவிர சிகிச்சை வசதிகளை பாதுகாத்தல் மற்றும் பாதுகாப்பான வெளியேற்றத்தை உறுதி செய்தல்.',
    ind_defense_title: 'பாதுகாப்பு நிறுவல்கள்',
    ind_defense_desc: 'பாதுகாப்பு உள்கட்டமைப்புக்கான முக்கியமான தீ பாதுகாப்பு.',
    ind_nuclear_title: 'அணுமின் நிலையங்கள்',
    ind_nuclear_desc: 'அணுசக்தி தளங்களுக்கான இணக்க அடிப்படையிலான தீயணைப்பு.',
    ind_aircraft_title: 'விமான வசதிகள்',
    ind_aircraft_desc: 'ஹேங்கர்கள் மற்றும் விண்வெளி அலகுகளுக்கான விரிவான பாதுகாப்பு.',

    // Licenses & Approvals
    home_licenses_badge: 'உரிமங்கள் மற்றும் அங்கீகாரங்கள்',
    home_licenses_title: 'நிபுணத்துவம் பெற்ற',
    home_licenses_title_span: 'உரிமங்கள் & அங்கீகாரங்கள்',
    home_licenses_desc: 'உங்கள் வணிகத்தை தணிக்கைக்கு தயாராக வைத்திருக்கும் சான்றளிக்கப்பட்ட, அரசாங்கத்தால் அங்கீகரிக்கப்பட்ட தீ பாதுகாப்பு உரிமங்கள் மற்றும் இணக்க சேவைகளை நாங்கள் வழங்குகிறோம்.',
    lic_noc_title: 'அரசு தீ NOC',
    lic_noc_desc: 'தீயணைப்புத் துறை அனுமதிகள் மற்றும் தடையில்லா சான்றிதழ்களுக்கான முழுமையான உதவி.',
    lic_iso_title: 'BIS & ISO சான்றளிக்கப்பட்டது',
    lic_iso_desc: 'தேசிய மற்றும் சர்வதேச தரங்களை பூர்த்தி செய்யும் முழுமையாக அங்கீகரிக்கப்பட்ட தயாரிப்புகள் மற்றும் சேவைகள்.',
    lic_audits_title: 'இணக்க தணிக்கைகள்',
    lic_audits_desc: 'ஆன்-சைட் ஆய்வுகள், இணக்க அறிக்கைகள் மற்றும் ஒப்புதல்களுக்கான ஆவணங்கள்.',
    lic_approvals_title: 'தொழில்துறை ஒப்புதல்கள்',
    lic_approvals_desc: 'தொழிற்சாலைகள், மால்கள், மருத்துவமனைகள், தகவல் தொழில்நுட்ப பூங்காக்கள் மற்றும் பிற தொழில்களுக்கான உரிமம்.',

    // Areas of Operation
    about_operation_badge: 'சேவை வரம்பு',
    about_operation_title: 'எங்கள் சேவை',
    about_operation_title_span: 'பகுதிகள்',
    about_operation_desc: 'தமிழ்நாட்டின் முக்கிய நகரங்களில் பிரீமியம் தீ பாதுகாப்பு உபகரணங்கள் மற்றும் இணக்க சேவைகளை வழங்குதல்.',
    about_operation_subtitle: 'வழங்கல் மற்றும் சேவை நெட்வொர்க்',

    home_about_badge: 'வரத விநாயகருக்கு வரவேற்கிறோம்',
    home_about_h1: 'உங்கள் நம்பகமான பங்காளி',
    home_about_h1_span: 'பாதுகாப்பில்',
    home_about_p1: 'தூத்துக்குடியை தளமாகக் கொண்டு தீ அணைப்பான்கள், ஹைட்ரன்ட் கூடுதல் பொருட்கள், தனிப்பட்ட பாதுகாப்பு உபகரணங்கள் மற்றும் தொழில்துறை பாதுகாப்பு பொருட்களை வழங்குகிறோம்.',
    home_about_p2: 'எங்கள் பொருட்கள் உயர்தர தரங்களை கண்டிப்பாக பின்பற்றுகின்றன — நீடித்த தன்மை மற்றும் வாடிக்கையாளர் திருப்திக்கு முழு முன்னுரிமை.',
    home_about_btn: 'எங்களை பற்றி மேலும் அறிக',

    stat_compliance: 'பாதுகாப்பு இணக்கம்',
    stat_experience: 'ஆண்டுகள் அனுபவம்',
    stat_staff: 'சான்றளிக்கப்பட்ட பணியாளர்கள்',
    stat_sites: 'செயலில் உள்ள தளங்கள்',
    stat_satisfaction: 'வாடிக்கையாளர் திருப்தி',
    stat_customers: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',

    home_process_badge: 'எங்கள் செயல்முறை',
    home_process_title: 'நாங்கள் எப்படி',
    home_process_title_span: 'செயல்படுகிறோம்',
    step_inspection: 'ஆய்வு',
    step_collection: 'சேகரிப்பு',
    step_execution: 'செயல்படுத்தல்',
    step_delivery: 'விநியோகம்',
    step_inspection_desc: 'முழுமையான தள மதிப்பீடு மற்றும் ஆபத்து அடையாளம்.',
    step_collection_desc: 'சான்றளிக்கப்பட்ட வசதிக்கு உபகரணங்களின் பாதுகாப்பான போக்குவரத்து.',
    step_execution_desc: 'சான்றளிக்கப்பட்ட நிரப்புதல் மற்றும் உயர் அழுத்த சோதனை.',
    step_delivery_desc: 'இறுதி தர சோதனை மற்றும் உடனடி விநியோகம்.',

    home_why_badge: 'ஏன் நாங்கள்',
    home_why_title: 'ஒவ்வொரு நொடியிலும்',
    home_why_title_span: 'நம்பகத்தன்மை',
    why_compliance: 'தர இணக்கம்',
    why_compliance_desc: 'தொழில்துறை பாதுகாப்பு தரங்களால் உரிமம் பெற்றது.',
    why_support: '24/7 ஆதரவு',

    // Home Testimonials
    home_testimonials_badge: 'வாடிக்கையாளர் கருத்துகள்',
    home_testimonials_title: 'நூற்றுக்கணக்கானோர்',
    home_testimonials_title_span: 'நம்பும்',
    home_testimonials_title_end: 'தமிழ்நாடு முழுவதும்',

    // Home Partners
    home_partners_badge: 'அங்கீகரிக்கப்பட்ட கூட்டாளிகள்',
    home_partners_title: 'நம்பகமான பிராண்டுகள் &',
    home_partners_title_span: 'சான்றிதழ்கள்',

    why_support_desc: 'அனைத்து பாதுகாப்பு தேவைகளுக்கும் தொடர்ச்சியான அவசர கால ஆதரவு.',
    why_certified: 'சான்றளிக்கப்பட்ட கையாளுதல்',
    why_certified_desc: 'பல தசாப்தங்கள் அனுபவம் கொண்ட நிபுணர் தொழில்நுட்பவியலாளர்கள்.',

    // Services
    services_badge: 'எங்கள் நிபுணத்துவம்',
    services_h1: 'முழுமையான',
    services_h1_span: 'பாதுகாப்பு',
    services_h1_end: 'சேவைகள்',
    services_intro: 'உங்கள் சூழலை முழுமையாக பாதுகாக்க, நாங்கள் விரிவான தொழில்முறை தீ பாதுகாப்பு சேவைகளை வழங்குகிறோம்.',

    svc_supply_title: 'தீ அணைப்பான் விநியோகம்',
    svc_supply_desc: 'தொழில்துறை, வணிக மற்றும் குடியிருப்பு பயன்பாட்டிற்கு ஏற்ற சான்றளிக்கப்பட்ட தீ அணைப்பான்களை வழங்குகிறோம்.',
    svc_refill_title: 'தீ அணைப்பான் நிரப்புதல்',
    svc_refill_desc: 'விரைவான தீ அடக்குதலுக்கான கடுமையான தொழில்துறை தரங்களுக்கு ஏற்ற உயர்தர நிரப்பு முகவர்கள்.',
    svc_service_title: 'தீ அணைப்பான் சேவை',
    svc_service_desc: 'தகுதிவாய்ந்த தொழில்நுட்ப வல்லுநர்களால் உங்கள் உபகரணம் எப்போதும் தயாராக இருப்பதை உறுதிசெய்ய அவ்வப்போது சேவை.',
    svc_hptest_title: 'உயர் அழுத்த சோதனை',
    svc_hptest_desc: 'தீவிர நிலைகளில் கொள்கலன் ஒருமைப்பாட்டை உறுதிசெய்யும் மேம்பட்ட ஹைட்ரோஸ்டாடிக் சோதனை.',
    svc_install_title: 'தீ பாதுகாப்பு உபகரண நிறுவல்',
    svc_install_desc: 'தீ பாதுகாப்பு குழாய்கள், ஹைட்ரன்ட்கள் மற்றும் முழுமையான தீ பாதுகாப்பு அமைப்புகளின் துல்லியமான நிறுவல்.',
    svc_amc_title: 'வருடாந்திர பராமரிப்பு ஒப்பந்தங்கள் (AMC)',
    svc_amc_desc: 'முழுமையான மன அமைதிக்காக முழுமையான அவ்வப்போது பராமரிப்பு சோதனைகள்.',
    svc_industrial_title: 'தொழில்துறை பாதுகாப்பு தீர்வுகள்',
    svc_industrial_desc: 'வெப்ப பாதுகாப்பு ஆடைகள், பாதுகாப்பு மழை நீராடிகள் மற்றும் விழுதல் பாதுகாப்பு கருவிகளில் நிபுணத்துவம் பெற்றவர்கள்.',

    industries_badge: 'நாங்கள் சேவை செய்யும் இடங்கள்',
    industries_title: 'சேவை பெறும்',
    industries_title_span: 'தொழில்கள்',

    ind_steel: 'எஃகு & இரும்பு தொழில்கள்',
    ind_thermal: 'அனல் மின் நிலையங்கள்',
    ind_construction: 'கட்டுமானம் & உள்கட்டமைப்பு',
    ind_engineering: 'பொறியியல் தொழில்கள்',
    ind_textile: 'ஜவுளி & ஆடை தொழில்கள்',
    ind_chemical: 'இரசாயன தொழில்கள்',
    ind_government: 'அரசு துறை',
    ind_education: 'கல்வி நிறுவனங்கள்',

    cta_title: 'உங்கள் வளாகத்தை பாதுகாக்க தயாரா?',
    cta_desc: 'உங்கள் தொழில்துறைக்கான தனிப்பயன் பாதுகாப்பு தீர்வுக்கு இன்றே தொடர்பு கொள்ளுங்கள்.',
    cta_btn: 'ஆலோசனை பதிவு',

    // Products
    products_badge: 'எங்கள் பட்டியல்',
    products_h1: 'உயரிய பாதுகாப்பு',
    products_h1_span: 'தயாரிப்புகள்',
    products_all: 'அனைத்தும்',
    enquire_now: 'இப்போது விசாரிக்கவும்',

    // About
    about_partner_badge: 'அங்கீகரிக்கப்பட்ட கூட்டாளிகள்',
    about_partner_title: 'நம்பகமான பிராண்டுகள் &',
    about_partner_title_span: 'சான்றிதழ்கள்',
    about_badge: 'எங்கள் நிறுவன சுயவிவரம்',
    about_h1: 'வரத விநாயகர்',
    about_h1_span: 'பாதுகாப்பு & தீ',
    about_p1: 'தூத்துக்குடியை தளமாகக் கொண்டு தீ அணைப்பான்கள், ஹைட்ரன்ட் கூடுதல் பொருட்கள், தனிப்பட்ட பாதுகாப்பு உபகரணங்கள் வழங்குகிறோம்.',
    about_p2: 'வாடிக்கையாளர் திருப்தி மற்றும் விரைவான சேவை வழங்கலில் கவனம் செலுத்தி உயர்தர தரங்களை பின்பற்றுகிறோம்.',
    about_check1: 'வடிவமைப்பிலிருந்து சோதனை வரை கண்டிப்பான தர கட்டுப்பாடு',
    about_check2: 'மேம்பட்ட தொழில்நுட்ப ஒருங்கிணைப்பு',
    about_check3: 'திறமையான நிபுணர்கள் மற்றும் அனுபவமிக்க குழு',
    about_check4: 'வாடிக்கையாளர் கேந்திர சேவை அணுகுமுறை',
    about_vision_title: 'எங்கள் தொலைநோக்கு',
    about_mission_title: 'எங்கள் நோக்கம்',
    about_quality_title: 'தர கொள்கை',

    about_vision_desc: 'மிகவும் மதிப்புமிக்க பாதுகாப்பு தீர்வு வழங்குநராக மாறுவது:',
    about_vision_1: 'முழுமையான பாதுகாப்பு அமைப்புகள்',
    about_vision_2: 'மேம்பட்ட தொழில்நுட்ப தீர்வுகள்',
    about_vision_3: 'தொடர்ச்சியான மேம்பாடு',
    about_vision_4: 'வாடிக்கையாளர் கவனம்',

    about_mission_desc: 'சிறப்பை நோக்கி உந்தும்:',
    about_mission_1: 'இந்தியாவின் பாதுகாப்பு துறையில் முதலிடம்',
    about_mission_2: 'புதுமை, தரம் மற்றும் சேவை சிறப்பு',
    about_mission_3: 'பாதுகாப்பு விழிப்புணர்வை ஊக்குவித்தல்',
    about_mission_4: 'உயர் மதிப்பு பொருட்கள் வழங்கல்',

    about_quality_desc: 'தரத்தை உறுதிப்படுத்துகிறோம்:',
    about_quality_1: 'வடிவமைப்பிலிருந்து சோதனை வரை கண்டிப்பான தர கட்டுப்பாடு',
    about_quality_2: 'மேம்பட்ட தொழில்நுட்ப ஒருங்கிணைப்பு',
    about_quality_3: 'திறமையான நிபுணர்கள் மற்றும் அனுபவமிக்க குழு',
    about_quality_4: 'வாடிக்கையாளர் கேந்திர சேவை அணுகுமுறை',

    // About Infrastructure
    infra_badge: 'உடல் திறன்',
    infra_title: 'எங்கள்',
    infra_title_span: 'உள்கட்டமைப்பு',
    infra_p1: 'வரத விநாயகர் பாதுகாப்பு & தீ, தூத்துக்குடியில் அமைந்த அதிநவீன வசதியைக் கொண்டுள்ளது, கனரக தொழில்துறை செயல்பாடுகளுக்கு முழுமையாக தயாராக உள்ளது.',
    infra_p2: 'எங்கள் உள்கட்டமைப்பு அதிக திறன் கொண்ட கிடங்கு, தொழில்முறை சேவை பகுதிகள் மற்றும் அர்ப்பணிக்கப்பட்ட ஹைட்ரோஸ்டாடிக் சோதனை அமைப்புகளை கொண்டுள்ளது. தேசிய மற்றும் தொழில்துறை பாதுகாப்பு வழிகாட்டுதல்களை பூர்த்தி செய்கிறது.',
    infra_check1: 'அதிக திறன் கொண்ட நவீன நிரப்புதல் பட்டறை',
    infra_check2: 'சான்றளிக்கப்பட்ட ஹைட்ரோஸ்டாடிக் சோதனை அமைப்புகள்',
    infra_check3: 'முழுமையாக அளவீடு செய்யப்பட்ட எடை சோதனை & அழுத்த கேஜ்கள்',

    // Contact
    contact_hero_badge: 'நேரடி தொடர்பு',
    contact_hero_title_1: 'எங்கள்',
    contact_hero_title_span: 'பாதுகாப்பு குழுவை',
    contact_hero_title_2: 'தொடர்புகொள்ளுங்கள்',
    contact_hero_desc: 'அவசர பாதுகாப்பு தேவை, அணைப்பான் நிரப்புதல் கோரிக்கை அல்லது அமைப்பு நிறுவல் வினா உள்ளதா? எங்கள் சான்றளிக்கப்பட்ட தீ பாதுகாப்பு பொறியாளர்கள் 24/7 தயாராக உள்ளனர்.',
    contact_call_btn: 'அவசர குழுவை அழைக்கவும்',
    contact_quote_btn: 'இலவச மதிப்பீடு கோரிக்கை',

    contact_support_badge: 'ஆதரவு விருப்பங்கள்',
    contact_support_title_1: 'ஒரு',
    contact_support_title_span: 'நேரடி தொடர்பு',
    contact_support_title_2: 'வினா அனுப்புக',

    contact_badge: 'தொடர்பு கொள்ளுங்கள்',
    contact_h1: 'தொடர்பு கொள்ளுங்கள்',
    contact_h1_span: 'பாதுகாப்பு',
    contact_h1_end: 'குழு',
    contact_phones: 'தொலைபேசி எண்கள்',
    contact_email: 'மின்னஞ்சல்',
    contact_email_btn: 'மின்னஞ்சல் அனுப்புக',
    contact_location: 'இருப்பிடம்',
    contact_location_addr: '112Q/3, முத்துகிருஷ்ணபுரம் 2வது தெரு, தூத்துக்குடி, தமிழ்நாடு',
    contact_emergency: 'அவசர சேவை',
    contact_emergency_avail: '24/7 கிடைக்கிறது',
    contact_emergency_desc: 'விரைவான அவசரகால பதிலுக்கு எங்கள் குழு எப்போதும் தயாராக உள்ளது.',
    contact_form_title: 'விலை கோரிக்கை',
    contact_name: 'முழு பெயர்',
    contact_name_placeholder: 'உங்கள் பெயர்',
    contact_phone_label: 'தொடர்பு எண்',
    contact_phone_placeholder: '+91 00000 00000',
    contact_service: 'தேவையான சேவை',
    contact_svc_refilling: 'நிரப்புதல்',
    contact_svc_servicing: 'சேவை',
    contact_svc_hptesting: 'உ.அ. சோதனை',
    contact_svc_supply: 'உபகரண விநியோகம்',
    contact_message: 'செய்தி',
    contact_message_placeholder: 'உங்கள் தேவைகளை பற்றி கூறுங்கள்...',
    contact_send: 'செய்தி அனுப்பு',
    contact_email_label: 'மின்னஞ்சல் முகவரி',
    contact_get_in_touch: 'தொடர்பு கொள்ள',
    contact_protect_desc: 'மிகவும் முக்கியமானவற்றைப் பாதுகாக்கத் தயாரா? இலவச ஆலோசனை மற்றும் தனிப்பயனாக்கப்பட்ட தீ பாதுகாப்புத் தீர்வுக்கு எங்கள் தீ பாதுகாப்பு நிபுணர்களைத் தொடர்பு கொள்ளுங்கள்.',
    contact_form_free_quote: 'இலவச மதிப்பீடு கோரிக்கை',

    // Footer
    footer_brand_sub: 'பாதுகாப்பு & தீ',
    footer_motto: '"தீயை நம்பாதீர்கள்! வரத விநாயகர் பாதுகாப்பை நம்புங்கள் - உங்கள் கட்டமைப்பு நலன் காவலர்."',
    footer_gstin_label: 'GSTIN பதிவு',
    footer_nav: 'வழிசெலுத்தல்',
    footer_terminals: 'தொடர்பு',
    footer_copy: 'VV பாதுகாப்பு & தீ. நிலை: பாதுகாப்பானது',
    footer_tagline: 'நம்பகத்தன்மை | நேர்மை | கட்டமைப்பு பாதுகாப்பு',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  const toggleLang = () => setLang(prev => prev === 'en' ? 'ta' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
